// Generated by ReScript, PLEASE EDIT WITH CARE


var $$NodeList = {};

var DomParser = {};

function parse(text) {
  var parser = new DOMParser();
  var rawParse = parser.parseFromString(text, "text/xml");
  var convertToObject = function (curr) {
    if (curr.childNodes.length === 0) {
      return {
              TAG: /* Leaf */0,
              _0: curr.nodeName,
              _1: curr.data
            };
    } else {
      return {
              TAG: /* Node */1,
              _0: curr.nodeName,
              _1: Array.from(curr.childNodes).filter(function (v) {
                        return v.nodeName !== "#comment";
                      }).filter(function (v) {
                      var tmp = false;
                      if (v.nodeName === "#text") {
                        var text = v.data;
                        tmp = text !== undefined ? text.trim() === "" : false;
                      }
                      return !tmp;
                    }).map(convertToObject)
            };
    }
  };
  return convertToObject(rawParse);
}

export {
  $$NodeList ,
  DomParser ,
  parse ,
  
}
/* No side effect */
