// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "rescript/lib/es6/array.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Parser from "../Parser.bs.js";
import * as PostCard from "../components/PostCard.bs.js";

function Home$Home(Props) {
  var match = React.useState(function () {
        return [];
      });
  var setPosts = match[1];
  var onSubmit = function (evt) {
    evt.preventDefault();
    var rssUrl = evt.target["rss-url"].value;
    var __x = fetch(rssUrl);
    var __x$1 = __x.then(function (res) {
          return res.text();
        });
    var __x$2 = __x$1.then(function (res) {
          var rss = Parser.parseFeed(res);
          Curry._1(setPosts, (function (_prev) {
                  return rss.posts;
                }));
          return Promise.resolve(undefined);
        });
    __x$2.catch(function (err) {
          console.log(err);
          return Promise.resolve(undefined);
        });
    
  };
  return React.createElement("div", undefined, React.createElement("h1", undefined, "RSS Reader"), React.createElement("form", {
                  onSubmit: onSubmit
                }, React.createElement("input", {
                      name: "rss-url",
                      placeholder: "RSS Feed URL",
                      type: "text"
                    }), React.createElement("input", {
                      type: "submit",
                      value: "Add feed"
                    })), $$Array.map((function (post) {
                    return React.createElement(PostCard.PostCard.make, {
                                post: post,
                                key: post.guid
                              });
                  }), match[0]));
}

var Home = {
  make: Home$Home
};

export {
  Home ,
  
}
/* react Not a pure module */
