// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function PostCard$PostCard(Props) {
  var post = Props.post;
  return React.createElement("div", {
              className: "card"
            }, React.createElement("small", undefined, post.pubDate), React.createElement("a", {
                  href: post.link,
                  target: "_blank"
                }, React.createElement("h2", undefined, post.title)));
}

var PostCard = {
  make: PostCard$PostCard
};

export {
  PostCard ,
  
}
/* react Not a pure module */
