// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Post$Post(Props) {
  var post = Props.post;
  return React.createElement("div", undefined, React.createElement("h2", undefined, post.title), React.createElement("div", {
                  dangerouslySetInnerHTML: {
                    __html: post.description
                  }
                }));
}

var Post = {
  make: Post$Post
};

export {
  Post ,
  
}
/* react Not a pure module */
