// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./pages/Home.bs.js";
import * as React from "react";
import LogoSvg from "./logo.svg";

import './App.css';
;

var logo = LogoSvg;

function App$App(Props) {
  return React.createElement(Home.Home.make, {});
}

var App = {
  make: App$App
};

export {
  logo ,
  App ,
  
}
/*  Not a pure module */
