// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Home$Home(Props) {
  return React.createElement("p", undefined, "hi");
}

var Home = {
  make: Home$Home
};

export {
  Home ,
  
}
/* react Not a pure module */
