// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Response = {};

function makeFetchOptions(method, headers, body, referrer, referrerPolicy, mode, credentials, cache, redirect, integrity, keepalive, signal, param) {
  return {
          method: method,
          headers: headers,
          body: body,
          referrer: referrer,
          referrerPolicy: referrerPolicy,
          mode: mode,
          credentials: credentials,
          cache: cache,
          redirect: redirect,
          integrity: integrity,
          keepalive: keepalive,
          signal: signal
        };
}

export {
  $$Response ,
  makeFetchOptions ,
  
}
/* No side effect */
