// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";
import ReportWebVitals from "./reportWebVitals";
import * as ServiceWorkerRegistration from "./serviceWorkerRegistration";

import './index.css';
;

function reportWebVitals(prim) {
  ReportWebVitals();
  
}

function registerServiceWorker(prim) {
  ServiceWorkerRegistration.register();
  
}

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(React.StrictMode, {
            children: React.createElement(App.App.make, {})
          }), root);
}

ServiceWorkerRegistration.register();

ReportWebVitals();

export {
  reportWebVitals ,
  registerServiceWorker ,
  
}
/*  Not a pure module */
