// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Id from "rescript/lib/es6/belt_Id.js";
import * as Belt_Set from "rescript/lib/es6/belt_Set.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";

var key = "feedURLs";

var cmp = Caml_obj.caml_compare;

var StringCmp = Belt_Id.MakeComparable({
      cmp: cmp
    });

function setFeedUrls(urls) {
  var rawUrls = JSON.stringify(Belt_Set.toArray(urls));
  localStorage.setItem(key, rawUrls);
  
}

function getFeedUrls(param) {
  var rawUrls = localStorage.getItem(key);
  if (rawUrls !== null) {
    return Belt_Set.fromArray(JSON.parse(rawUrls), StringCmp);
  }
  var urls = Belt_Set.make(StringCmp);
  setFeedUrls(urls);
  return urls;
}

export {
  key ,
  StringCmp ,
  setFeedUrls ,
  getFeedUrls ,
  
}
/* StringCmp Not a pure module */
